version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Go-Hello-World"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g3ktqzvdqtnl"
s3_prefix = "Go-Hello-World"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
